version: '3.5'
services:
  upload-media:
      build:
        context: .
        dockerfile: Dockerfile
      network_mode: host
      environment:

#        MONGO_HOST: cloud-dev-mongo-node-1
        MONGO_HOST: cloud-user-mongo-node-1,cloud-user-mongo-node-2,cloud-user-mongo-node-3  # prod
        MONGO_PASSWORD: 8J3T2i7sA0q3ds #prod
        MONGO_PORT: 27017
        MONGO_USER: usr
#        MONGO_PASSWORD: SWLMjcR9uTGPQ7qj

      restart: on-failure
